package atomdance.app.modules.finance.model;

import atomdance.app.common.utils.Money;
import atomdance.app.modules.person.model.Person;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;


/**
 * Money somebody actually handed over. The only place in the system that holds cash.
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Table(name = "deposits",
		uniqueConstraints = @UniqueConstraint(name = "uk_deposits_number", columnNames = "number"),
		indexes = @Index(name = "idx_deposits_received_at", columnList = "received_at"))
public class Deposit {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private UUID id;

	/**
	 * A short handle a manager can quote off a receipt, shown as "D-1234" - see {@link #getCode()}.
	 */
	@Column(name = "number", nullable = false, insertable = false, updatable = false, columnDefinition = "bigint generated by default as identity")
	@Generated(event = EventType.INSERT)
	@Setter(AccessLevel.NONE)
	private Long number;

	/**
	 * Everybody this money was handed over for.
	 */
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "deposit_covered_persons", joinColumns = @JoinColumn(name = "deposit_id"), inverseJoinColumns = @JoinColumn(name = "person_id"))
	@BatchSize(size = 64)
	@Builder.Default
	private Set<Person> coveredPersons = new LinkedHashSet<>();

	@Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal totalAmount = Money.ZERO;

	@Enumerated(EnumType.STRING)
	@Column(name = "payment_method", nullable = false, length = 16)
	private PaymentMethod paymentMethod;

	@Column(name = "received_at", nullable = false)
	private Instant receivedAt;

	/**
	 * Which account this money was paid into, and so the only charges it is allowed to settle.
	 */
	@Enumerated(EnumType.STRING)
	@Column(name = "scope", nullable = false, length = 16)
	private DepositScope scope;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 16)
	@Builder.Default
	private DepositOrigin origin = DepositOrigin.COUNTER;

	@Column(length = 512)
	private String note;

	@Column(name = "created_by_user_id")
	private UUID createdByUserId;

	@Column(nullable = false)
	private Instant createdAt;

	/**
	 * How this money was spent.
	 */
	@OneToMany(mappedBy = "deposit", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	@Builder.Default
	private List<PaymentSettlement> settlements = new ArrayList<>();


	@PrePersist
	void onCreate() {
		if (createdAt == null) {
			createdAt = Instant.now();
		}

		if (receivedAt == null) {
			receivedAt = createdAt;
		}
	}


	public String getCode() {
		return DepositCode.format(number);
	}


	/**
	 * The people this money was for, in the order screens list them.
	 */
	public List<Person> getCoveredPersonsInDisplayOrder() {
		return coveredPersons.stream().sorted(DISPLAY_ORDER).toList();
	}


	public List<UUID> getCoveredPersonIds() {
		return getCoveredPersonsInDisplayOrder().stream().map(Person::getId).toList();
	}


	/**
	 * Whether this money is allowed to settle a charge on the given list.
	 */
	public boolean maySettleOn(PaymentList list) {
		return scope == list.scope();
	}


	public BigDecimal getAllocatedAmount() {
		BigDecimal total = Money.ZERO;

		for (PaymentSettlement settlement : settlements) {
			total = Money.add(total, settlement.getAmount());
		}

		return total;
	}


	public BigDecimal getUnallocatedAmount() {
		return Money.atLeastZero(Money.subtract(totalAmount, getAllocatedAmount()));
	}


	public boolean isFullyAllocated() {
		return !Money.isPositive(getUnallocatedAmount());
	}


	public void addSettlement(PaymentSettlement settlement) {
		settlement.setDeposit(this);
		settlements.add(settlement);
	}


	public void removeSettlement(PaymentSettlement settlement) {
		settlements.remove(settlement);
	}


	private static final Comparator<Person> DISPLAY_ORDER = Comparator
			.comparing(Person::getLastName, Comparator.nullsLast(String.CASE_INSENSITIVE_ORDER))
			.thenComparing(Person::getName, Comparator.nullsLast(String.CASE_INSENSITIVE_ORDER))
			.thenComparing(Person::getId);
}
