package atomdance.app.modules.finance.model;

import atomdance.app.common.utils.Money;
import atomdance.app.modules.person.model.Person;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.YearMonth;
import java.util.*;


/**
 * Money somebody actually handed over. The only place in the system that holds cash.
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Table(name = "deposits",
		uniqueConstraints = @UniqueConstraint(name = "uk_deposits_number", columnNames = "number"),
		indexes = {
				@Index(name = "idx_deposits_payer_id", columnList = "payer_id"),
				@Index(name = "idx_deposits_booked", columnList = "booked_year, booked_month"),
				@Index(name = "idx_deposits_received_at", columnList = "received_at")
		})
public class Deposit {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private UUID id;

	/**
	 * A short handle a manager can quote off a receipt, shown as "D-1234" - see {@link #getCode()}.
	 */
	@Column(name = "number", nullable = false, insertable = false, updatable = false, columnDefinition = "bigint generated by default as identity")
	@Generated(event = EventType.INSERT)
	@Setter(AccessLevel.NONE)
	private Long number;

	/**
	 * Who handed the money over. The first person a manager picks at the counter.
	 */
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "payer_id", nullable = false)
	private Person payer;

	/**
	 * Everybody the manager said this money was for, kept so leftover credit can be re-planned later
	 * against the same people without them having to remember the selection.
	 */
	@ElementCollection(fetch = FetchType.LAZY)
	@CollectionTable(name = "deposit_covered_persons", joinColumns = @JoinColumn(name = "deposit_id"))
	@Column(name = "person_id", nullable = false)
	@BatchSize(size = 64)
	@Builder.Default
	private Set<UUID> coveredPersonIds = new HashSet<>();

	@Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal totalAmount = Money.ZERO;

	@Enumerated(EnumType.STRING)
	@Column(name = "payment_method", nullable = false, length = 16)
	private PaymentMethod paymentMethod;

	@Column(name = "received_at", nullable = false)
	private Instant receivedAt;

	/**
	 * The accounting period this cash belongs to, defaulting to the month it was received in.
	 */
	@Column(name = "booked_year", nullable = false)
	private Integer bookedYear;

	@Column(name = "booked_month", nullable = false)
	private Integer bookedMonth;

	/**
	 * Which of the two monthly sheets this money was taken for: {@code true} tournament, {@code false} ordinary
	 * classes, {@code null} neither - a handover recorded straight against a charge on an ad-hoc sheet.
	 */
	@Column(name = "is_for_tournament")
	private Boolean forTournament;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 16)
	@Builder.Default
	private DepositOrigin origin = DepositOrigin.COUNTER;

	@Column(length = 512)
	private String note;

	@Column(name = "created_by_user_id")
	private UUID createdByUserId;

	@Column(nullable = false)
	private Instant createdAt;

	/**
	 * How this money was spent.
	 */
	@OneToMany(mappedBy = "deposit", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	@Builder.Default
	private List<PaymentSettlement> settlements = new ArrayList<>();


	@PrePersist
	void onCreate() {
		if (createdAt == null) {
			createdAt = Instant.now();
		}

		if (receivedAt == null) {
			receivedAt = createdAt;
		}
	}


	/**
	 * How {@link #number} is written and spoken: "D-1234".
	 */
	public String getCode() {
		return DepositCode.format(number);
	}


	public YearMonth bookedFor() {
		if (bookedYear == null || bookedMonth == null) {
			return null;
		}

		return YearMonth.of(bookedYear, bookedMonth);
	}


	public void bookFor(YearMonth month) {
		bookedYear = month.getYear();
		bookedMonth = month.getMonthValue();
	}


	/**
	 * @return whether this deposit's cash counts as income for the given month
	 */
	public boolean isBookedFor(YearMonth month) {
		return month != null && month.equals(bookedFor());
	}


	/**
	 * The monthly sheet this money may be spent on, or {@code null} when it was not taken for one.
	 */
	public ListType scopeType() {
		return forTournament == null ? null : ListType.standardFor(forTournament);
	}


	/**
	 * Whether this money is allowed to settle a charge on the given list.
	 */
	public boolean maySettleOn(PaymentList list) {
		return forTournament == null || list.getType() == scopeType();
	}


	public BigDecimal getAllocatedAmount() {
		BigDecimal total = Money.ZERO;

		for (PaymentSettlement settlement : settlements) {
			total = Money.add(total, settlement.getAmount());
		}

		return total;
	}


	public BigDecimal getUnallocatedAmount() {
		return Money.atLeastZero(Money.subtract(totalAmount, getAllocatedAmount()));
	}


	public boolean isFullyAllocated() {
		return !Money.isPositive(getUnallocatedAmount());
	}


	public void addSettlement(PaymentSettlement settlement) {
		settlement.setDeposit(this);
		settlements.add(settlement);
	}


	public void removeSettlement(PaymentSettlement settlement) {
		settlements.remove(settlement);
	}
}
