package atomdance.app.modules.finance.model;

import atomdance.app.common.utils.Money;
import atomdance.app.modules.group.model.Group;
import atomdance.app.modules.group.model.Membership;
import atomdance.app.modules.person.model.Person;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;


/**
 * One billable item on one list: what a person owes for a single group, or a one-off charge added by hand.
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Table(name = "payments",
		uniqueConstraints = @UniqueConstraint(name = "uk_payments_number", columnNames = "number"),
		indexes = {
				@Index(name = "idx_payments_list_id", columnList = "list_id"),
				@Index(name = "idx_payments_person_id", columnList = "person_id"),
				@Index(name = "idx_payments_group_id", columnList = "group_id")
		})
public class Payment {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private UUID id;

	/**
	 * A short handle a person can say out loud, shown as "P-1234" - see {@link #getCode()}.
	 */
	@Column(name = "number", nullable = false, insertable = false, updatable = false, columnDefinition = "bigint generated by default as identity")
	@Generated(event = EventType.INSERT)
	@Setter(AccessLevel.NONE)
	private Long number;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "list_id", nullable = false)
	private PaymentList list;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "person_id", nullable = false)
	private Person person;

	@Enumerated(EnumType.STRING)
	@Column(name = "charge_kind", nullable = false, length = 32)
	private PaymentChargeKind chargeKind;

	/**
	 * The group being billed. Always set on a monthly sheet and {@code null} on an ad-hoc one, whose charges are described rather than derived from a group.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	private Group group;

	/**
	 * Where the rate came from. Held alongside the group so the payment still names its group if the membership is ever removed.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "membership_id")
	private Membership membership;

	/**
	 * What the charge is for. Set by hand on a one-off; a label for the group otherwise.
	 */
	@Column(length = 255)
	private String description;

	/**
	 * The rate charged - a monthly fee, or the price of one class. Snapshotted from the group or the
	 * individually agreed amount, so a later price change does not rewrite history.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal unitCost = Money.ZERO;

	/**
	 * 1 for a monthly fee. For a per-class group, the number of classes attended.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal quantity = BigDecimal.ONE;

	@Column(nullable = false, precision = 5, scale = 2)
	@Builder.Default
	private BigDecimal discountPercent = Money.ZERO;

	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal discountAmount = Money.ZERO;

	/**
	 * The total owed, held as a stored figure rather than derived on read.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal amountToPay = Money.ZERO;

	/**
	 * A cache of {@link #settlements}, refreshed by {@link #recalculateSettledAmount()} on every settlement write.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal amountSettled = Money.ZERO;

	/**
	 * Camp lists only.
	 */
	@Column(name = "contract_returned", nullable = false)
	@Builder.Default
	private boolean contractReturned = false;

	@Column(length = 512)
	private String note;

	/**
	 * What has been paid towards this, and out of which deposit.
	 */
	@OneToMany(mappedBy = "payment", fetch = FetchType.LAZY)
	@Builder.Default
	private List<PaymentSettlement> settlements = new ArrayList<>();


	/**
	 * How {@link #number} is written and spoken: "P-1234".
	 */
	public String getCode() {
		return PaymentCode.format(number);
	}


	/**
	 * The charge before any discount.
	 */
	public BigDecimal getGross() {
		return Money.multiply(unitCost, quantity);
	}


	/**
	 * The one way {@link #amountToPay} is arrived at.
	 */
	public void applyDiscount(BigDecimal percent) {
		BigDecimal gross = getGross();

		discountPercent = Money.normalize(percent);
		discountAmount = Money.percentOf(gross, discountPercent);
		amountToPay = Money.atLeastZero(Money.subtract(gross, discountAmount));
	}


	/**
	 * Brings {@link #amountSettled} back into line with the settlements actually recorded.
	 */
	public void recalculateSettledAmount() {
		BigDecimal total = Money.ZERO;

		for (PaymentSettlement settlement : settlements) {
			total = Money.add(total, settlement.getAmount());
		}

		amountSettled = total;
	}


	/**
	 * Takes a settlement onto this payment and numbers it.
	 */
	public void addSettlement(PaymentSettlement settlement) {
		settlement.setPayment(this);

		if (settlement.getNumber() == null) {
			settlement.setNumber(nextSettlementNumber());
		}

		settlements.add(settlement);
		recalculateSettledAmount();
	}


	private long nextSettlementNumber() {
		long highest = 0;

		for (PaymentSettlement settlement : settlements) {
			Long number = settlement.getNumber();

			if (number != null && number > highest) {
				highest = number;
			}
		}

		return highest + 1;
	}


	public void removeSettlement(PaymentSettlement settlement) {
		settlements.remove(settlement);
		recalculateSettledAmount();
	}


	/**
	 * What is still owed, floored at zero.
	 */
	public BigDecimal getOutstanding() {
		return Money.atLeastZero(Money.subtract(amountToPay, amountSettled));
	}


	public boolean isSettled() {
		return !Money.isGreaterThan(amountToPay, amountSettled);
	}


	/**
	 * Whether anything has been paid towards this at all, which is what stops it being deleted by a recalculation or a list deletion.
	 */
	public boolean holdsSettlements() {
		return Money.isPositive(amountSettled);
	}


	/**
	 * A label for a report or an audit line: the group's name, or the one-off's own description.
	 */
	public String getLabel() {
		if (description != null && !description.isBlank()) {
			return description;
		}

		return group == null ? "" : group.getName();
	}
}
