package atomdance.app.modules.finance.model;

import atomdance.app.common.utils.Money;
import atomdance.app.modules.group.model.Group;
import atomdance.app.modules.group.model.Membership;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.util.UUID;

@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Table(name = "payment_lines", uniqueConstraints = @UniqueConstraint(name = "uk_payment_lines_number", columnNames = "number"),
		indexes = @Index(name = "idx_payment_lines_payment_id", columnList = "payment_id"))
public class PaymentLine {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private UUID id;

	/**
	 * The charge's half of "P-1234/5678" - see {@link #getCode()}.
	 */
	@Column(name = "number", nullable = false, insertable = false, updatable = false, columnDefinition = "bigint generated by default as identity")
	@Generated(event = EventType.INSERT)
	@Setter(AccessLevel.NONE)
	private Long number;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "payment_id", nullable = false)
	private Payment payment;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 32)
	private PaymentLineKind kind;

	/**
	 * The membership this charge came from, or {@code null} for a hand-added one-off.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "membership_id")
	private Membership membership;

	/**
	 * Held alongside the membership so the line still names its group if the membership is ever removed.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	private Group group;

	/**
	 * What the line is for. Set by hand on a one-off charge; a label for the group otherwise.
	 */
	@Column(length = 255)
	private String description;

	/**
	 * The rate charged - a monthly fee, or the price of one class. Snapshotted from the group or the
	 * individually agreed amount.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal unitCost = Money.ZERO;

	/**
	 * 1 for a monthly fee. For a per-class group, the number of classes attended, which a manager enters
	 * and a recalculation must preserve rather than derive.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal quantity = BigDecimal.ONE;

	@Column(nullable = false, precision = 5, scale = 2)
	@Builder.Default
	private BigDecimal discountPercent = Money.ZERO;

	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal discountAmount = Money.ZERO;

	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal subtotal = Money.ZERO;


	public String getCode() {
		return payment == null ? null : PaymentCode.formatLine(payment.getCode(), number);
	}

	public BigDecimal getGross() {
		return Money.multiply(unitCost, quantity);
	}

	public void applyDiscount(BigDecimal percent) {
		BigDecimal gross = getGross();

		discountPercent = Money.normalize(percent);
		discountAmount = Money.percentOf(gross, discountPercent);
		subtotal = Money.atLeastZero(Money.subtract(gross, discountAmount));
	}
}
