package atomdance.app.modules.finance.model;

import atomdance.app.common.utils.Money;
import atomdance.app.modules.person.model.Person;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * One person's entry on one list: what they owe, and what they have handed over.
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@Table(name = "payments",
		uniqueConstraints = {
				@UniqueConstraint(name = "uk_payments_list_person", columnNames = {"list_id", "person_id"}),
				@UniqueConstraint(name = "uk_payments_number", columnNames = "number")
		},
		indexes = {
				@Index(name = "idx_payments_list_id", columnList = "list_id"),
				@Index(name = "idx_payments_person_id", columnList = "person_id"),
				@Index(name = "idx_payments_settled_by", columnList = "settled_by_payment_id")
		})
public class Payment {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private UUID id;

	/**
	 * A short handle a person can say out loud, shown as "P-1234" - see {@link #getCode()}.
	 */
	@Column(name = "number", nullable = false, insertable = false, updatable = false, columnDefinition = "bigint generated by default as identity")
	@Generated(event = EventType.INSERT)
	@Setter(AccessLevel.NONE)
	private Long number;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "list_id", nullable = false)
	private PaymentList list;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "person_id", nullable = false)
	private Person person;

	/**
	 * The total owed, held as a stored figure rather than derived on read.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal amountToPay = Money.ZERO;

	/**
	 * What was actually handed over.
	 */
	@Column(nullable = false, precision = 12, scale = 2)
	@Builder.Default
	private BigDecimal amountPaid = Money.ZERO;

	@Enumerated(EnumType.STRING)
	@Column(length = 16)
	private PaymentMethod paymentMethod;

	private Instant paidAt;

	/**
	 * Marks a row that reads as settled but holds no money of its own.
	 */
	@Column(name = "is_fake_payment", nullable = false)
	@Builder.Default
	private boolean isFakePayment = false;

	/**
	 * The payment whose overpayment settled this one. Only set alongside {@link #isFakePayment}.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "settled_by_payment_id")
	private Payment settledByPayment;

	/**
	 * Camp lists only.
	 */
	@Column(name = "contract_returned", nullable = false)
	@Builder.Default
	private boolean contractReturned = false;

	@Column(length = 512)
	private String note;

	/**
	 * Why {@link #amountToPay} is what it is.
	 */
	@OneToMany(mappedBy = "payment", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	@Builder.Default
	private List<PaymentLine> lines = new ArrayList<>();


	public void addLine(PaymentLine line) {
		line.setPayment(this);
		lines.add(line);
	}

	/**
	 * How {@link #number} is written and spoken: "P-1234".
	 */
	public String getCode() {
		return PaymentCode.format(number);
	}

	/**
	 * What is still owed, floored at zero so an overpayment does not read as a negative debt.
	 */
	public BigDecimal getOutstanding() {
		return Money.atLeastZero(Money.subtract(amountToPay, amountPaid));
	}

	public boolean isSettled() {
		return !Money.isGreaterThan(amountToPay, amountPaid);
	}

	public BigDecimal getOverpayment() {
		return Money.atLeastZero(Money.subtract(amountPaid, amountToPay));
	}

	public void recalculateAmountToPay() {
		BigDecimal total = Money.ZERO;

		for (PaymentLine line : lines) {
			total = Money.add(total, line.getSubtotal());
		}

		amountToPay = total;
	}
}
