package atomdance.app.modules.finance.model;

public enum PaymentLineKind {

	/**
	 * A flat monthly group fee.
	 */
	MEMBERSHIP_MONTHLY,

	/**
	 * A per-class group fee.
	 */
	MEMBERSHIP_PER_CLASS,

	/**
	 * A one-off charge added by hand for this month only. Regenerated by nothing, and no discount applies to it.
	 */
	ONE_TIME;

	public boolean isMembershipDerived() {
		return this != ONE_TIME;
	}

}
