package atomdance.app.modules.activity.model;

public enum ActivityType {

	EMAIL_VERIFICATION,
	EMAIL_DELIVERY,
	SYSTEM_CLEANUP,
	USER_CREATION,
	USER_MANAGEMENT,

	PERSON_PREVIEW,
	FAMILY_PREVIEW,
	GROUP_PREVIEW,
	MEMBERSHIP_PREVIEW,
	INSTRUCTOR_PREVIEW,
	DISCOUNT_PREVIEW,

	PERSON_MANAGEMENT,
	FAMILY_MANAGEMENT,
	GROUP_MANAGEMENT,
	MEMBERSHIP_MANAGEMENT,
	INSTRUCTOR_MANAGEMENT,
	DISCOUNT_MANAGEMENT,

	LIST_PREVIEW,
	PAYMENT_PREVIEW,
	TRANSACTION_PREVIEW,

	LIST_MANAGEMENT,
	PAYMENT_MANAGEMENT,
	TRANSACTION_MANAGEMENT
}
