package atomdance.app.modules.finance.payment.model;

/**
 * What a {@link Payment} is charging for.
 */
public enum PaymentChargeKind {

	/**
	 * A flat monthly fee for one group.
	 */
	MEMBERSHIP_MONTHLY,

	/**
	 * One group billed by the class, where the quantity is how many classes were attended.
	 */
	MEMBERSHIP_PER_CLASS,

	/**
	 * A charge added by hand for this list only, belonging to no group. Regenerated by nothing, and no discount applies to it.
	 */
	ONE_TIME;


	public boolean isMembershipDerived() {
		return this != ONE_TIME;
	}


	/**
	 * The kind a group's billing type calls for.
	 */
	public static PaymentChargeKind forGroup(boolean perClass) {
		return perClass ? MEMBERSHIP_PER_CLASS : MEMBERSHIP_MONTHLY;
	}
}
